task-7
1van0v/product-shop-services pull request #5
Opened 2021-10-17 18:36 UTC by 1van0v

not done. Please give me one or two days

2021-10-21 06:31 UTC, vladshcherbin requested changes
проверил, выглядит хорошо, только поправить dotenv переменные как указано в задании

2021-10-21 06:31 UTC, vladshcherbin commented on authorization-service/handler.js
> +import dotenv from 'dotenv';
dotenv не должно быть в этом файле, переменные прокидывает сам serverless и aws

2021-10-21 06:31 UTC, vladshcherbin commented on authorization-service/handler.js
> +  return username === process.env.username && password === process.env.password;
по заданию 7.1, нужно использовать не `username` и `password` переменные, а переменную вида

vasiapupkin=TEST_PASSWORD

2021-10-21 19:06 UTC, 1van0v commented on authorization-service/handler.js
> +import dotenv from 'dotenv';
fixed in bd5ec2f0144467255c94c465cb34ed7544174aa3

2021-10-21 19:06 UTC, 1van0v commented on authorization-service/handler.js
> +  return username === process.env.username && password === process.env.password;
fixed in bd5ec2f0144467255c94c465cb34ed7544174aa3

2021-10-22 04:01 UTC, vladshcherbin commented on authorization-service/handler.js
> +  return username in process.env && password === process.env[username];
можно заменить на короткое:

```js
return process.env?.[username] === password
```

2021-10-22 04:02 UTC, vladshcherbin commented
отлично, всё исправлено 👍

2021-10-24 20:27 UTC, 1van0v commented on authorization-service/handler.js
> +  return username in process.env && password === process.env[username];
fixed here 00a8229a6549f06dfda2d6840195e38472c6c46c

2021-10-24 20:27 UTC, merged